---
title: "GLM"
author: "Taiki Yamashita"
date: "2024-06-26"
output: html_document
---

```{r, echo=FALSE}
install.packages(c("MASS", "lattice", "sandwich", "boot", "COUNT", "pscl", "logistf"), packagesdependencies=TRUE)
library(MASS)
library(lattice)
library(sandwich)
library(boot)
library(COUNT)
library(pscl)
library(logistf)
library(ggplot2)
```

# Logistic Regression
There are cases that the outcome for a given set of predictors can only get positive values or values in the interval (0, 1)

# Link Fuction
Mean of Y: 0 < mean < 1
odd functions, logit functions

```{r}
mydata <- read.csv("https://stats.oarc.ucla.edu/stat/data/binary.csv")
```


```{r}
# these two are GRE and GPA included
glm.mod <- glm(admit ~ gre, family = binomial(link = "logit"), data = mydata)
summary(glm.mod)

glm.mod.2 <- glm(admit ~ gre + gpa, family = binomial(link = "logit"), data = mydata)
summary(glm.mod.2)

# this one is just for the GPA
just_gpa <- glm(admit ~ gpa, family = binomial(link = "logit"), data = mydata)
summary(just_gpa)
```










```{r}
library(count)
data("rwm1983")
head(rwn1984)
summary
```



